import type { Parking } from './types'

export const PARKINGS: Parking[] = [
  {
    id: 'osm-way-852523325',
    name: '038 Parking Center',
    zone: 'Qendër',
    address: 'Qendër, Prishtinë',
    capacity: 705,
    spaces: null,
    status: 'unknown',
    pricePerHour: null,
    distanceMeters: 286,
    driveMinutes: 3,
    confidence: 'high',
    updatedMinutesAgo: 0,
    type: 'public',
    open24h: false,
    covered: true,
    cardPayment: false,
    evCharging: false,
    accessible: false,
    free: false,
    coordinates: { lat: 42.6565413, lng: 21.1605923 },
    access: 'permissive',
    osmUrl: 'https://www.openstreetmap.org/way/852523325',
    source: 'openstreetmap',
  },
  {
    id: 'osm-way-844301764',
    name: 'Parkingu publik Ramiz Sadiku',
    zone: 'Ulpianë',
    address: 'Stadiumi Ramiz Sadiku, Prishtinë',
    capacity: 120,
    spaces: null,
    status: 'unknown',
    pricePerHour: 0.3,
    distanceMeters: 1422,
    driveMinutes: 7,
    confidence: 'high',
    updatedMinutesAgo: 0,
    type: 'public',
    open24h: false,
    covered: false,
    cardPayment: false,
    evCharging: false,
    accessible: false,
    free: false,
    coordinates: { lat: 42.6458952, lng: 21.1572768 },
    access: 'public',
    osmUrl: 'https://www.openstreetmap.org/way/844301764',
    source: 'openstreetmap',
  },
]

export const defaultParking = PARKINGS[0]
