import type { Parking } from './types'

export const defaultParking: Parking = {
  id: 'test-parking',
  name: 'Test Parking',
  zone: 'Prishtine',
  address: 'Test address',
  capacity: 100,
  spaces: null,
  status: 'unknown',
  pricePerHour: null,
  distanceMeters: 0,
  driveMinutes: 1,
  confidence: 'high',
  updatedMinutesAgo: 0,
  type: 'public',
  open24h: true,
  covered: false,
  cardPayment: false,
  evCharging: false,
  accessible: false,
  free: false,
  coordinates: { lat: 42.66, lng: 21.16 },
  access: 'public',
  source: 'community',
}
